In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [ ]:
paragraph="""Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] (listen); born 17 September 1950)[b] is an Indian politician who has served as the 14th Prime Minister of India since May 2014. Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister from outside the Indian National Congress.

Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at age eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.[c] """

In [ ]:
paragraph

'Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] (listen); born 17 September 1950)[b] is an Indian politician who has served as the 14th Prime Minister of India since May 2014. Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister from outside the Indian National Congress.\n\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at age eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time w

In [ ]:
#tokenization
nltk.download('punkt')
sentences=nltk.sent_tokenize(paragraph)
sentences

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] (listen); born 17 September 1950)[b] is an Indian politician who has served as the 14th Prime Minister of India since May 2014.',
 'Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi.',
 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation.',
 'He is the longest-serving prime minister from outside the Indian National Congress.',
 'Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.',
 'He was introduced to the RSS at age eight.',
 'His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated.',
 'At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so.

In [ ]:
type(sentences)

list

In [ ]:
len(sentences)

11

In [ ]:
stemmer=PorterStemmer()
stemmer.stem('national')

'nation'

In [ ]:
from nltk.stem import WordNetLemmatizer


In [ ]:

 nltk.download('wordnet')

lemmatizer=WordNetLemmatizer()
lemmatizer.lemmatize('history')

[nltk_data] Downloading package wordnet to /root/nltk_data...


'history'

In [ ]:
import re
corpus=[]
for i in range(len(sentences)):
  review=re.sub('[^a-zA-Z]',' ',sentences[i])
  review=review.lower()
  corpus.append(review)

In [ ]:
corpus

['narendra damodardas modi  gujarati    n  end   d mod   d s  modi    listen   born    september       b  is an indian politician who has served as the   th prime minister of india since may      ',
 'modi was the chief minister of gujarat from      to      and is the member of parliament  mp  for varanasi ',
 'he is a member of the bharatiya janata party  bjp  and of the rashtriya swayamsevak sangh  rss   a right wing hindu nationalist paramilitary volunteer organisation ',
 'he is the longest serving prime minister from outside the indian national congress ',
 'modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education ',
 'he was introduced to the rss at age eight ',
 'his account of helping his father sell tea at the vadnagar railway station has not been reliably corroborated ',
 'at age     he was married to jashodaben modi  whom he abandoned soon after  only publicly acknowledging her four decades later when legally required to do so 

In [ ]:
for i in corpus:
  print(i)

narendra damodardas modi  gujarati    n  end   d mod   d s  modi    listen   born    september       b  is an indian politician who has served as the   th prime minister of india since may      
modi was the chief minister of gujarat from      to      and is the member of parliament  mp  for varanasi 
he is a member of the bharatiya janata party  bjp  and of the rashtriya swayamsevak sangh  rss   a right wing hindu nationalist paramilitary volunteer organisation 
he is the longest serving prime minister from outside the indian national congress 
modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education 
he was introduced to the rss at age eight 
his account of helping his father sell tea at the vadnagar railway station has not been reliably corroborated 
at age     he was married to jashodaben modi  whom he abandoned soon after  only publicly acknowledging her four decades later when legally required to do so 
modi became a full time worke

In [ ]:
nltk.download('stopwords')
for i in corpus:
  words=nltk.word_tokenize(i)
  for word in words:
      if word not in set(stopwords.words('english')):
          print(stemmer.stem(word))

narendra
damodarda
modi
gujarati
n
end
mod
modi
listen
born
septemb
b
indian
politician
serv
th
prime
minist
india
sinc
may
modi
chief
minist
gujarat
member
parliament
mp
varanasi
member
bharatiya
janata
parti
bjp
rashtriya
swayamsevak
sangh
rss
right
wing
hindu
nationalist
paramilitari
volunt
organis
longest
serv
prime
minist
outsid
indian
nation
congress
modi
born
rais
vadnagar
northeastern
gujarat
complet
secondari
educ
introduc
rss
age
eight
account
help
father
sell
tea
vadnagar
railway
station
reliabl
corrobor
age
marri
jashodaben
modi
abandon
soon
publicli
acknowledg
four
decad
later
legal
requir
modi
becam
full
time
worker
rss
gujarat
rss
assign
bjp
held
sever
posit
within
parti
hierarchi
rise
rank
gener
secretari
c


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
import re
corpus=[]
for i in range(len(sentences)):
  review=re.sub('[^a-zA-Z]',' ' ,sentences[i])
  review=review.lower()
  review=review.split()
  review=[lemmatizer.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
  review=' '.join(review)
  corpus.append(review)


In [ ]:
nltk.download('stopwords')
for i in corpus:
  words=nltk.word_tokenize(i)
  for word in words:
      if word not in set(stopwords.words('english')):
          print(lemmatizer.lemmatize(word))

narendra
damodardas
modi
gujarati
n
end
mod
modi
listen
born
september
b
indian
politician
served
th
prime
minister
india
since
may
modi
chief
minister
gujarat
member
parliament
mp
varanasi
member
bharatiya
janata
party
bjp
rashtriya
swayamsevak
sangh
r
right
wing
hindu
nationalist
paramilitary
volunteer
organisation
longest
serving
prime
minister
outside
indian
national
congress
modi
born
raised
vadnagar
northeastern
gujarat
completed
secondary
education
introduced
r
age
eight
account
helping
father
sell
tea
vadnagar
railway
station
reliably
corroborated
age
married
jashodaben
modi
abandoned
soon
publicly
acknowledging
four
decade
later
legally
required
modi
became
full
time
worker
r
gujarat
r
assigned
bjp
held
several
position
within
party
hierarchy
rising
rank
general
secretary
c


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(binary=True,ngram_range=(3, 3))


In [ ]:
x=cv.fit_transform(corpus)

In [ ]:
x

<11x86 sparse matrix of type '<class 'numpy.int64'>'
	with 102 stored elements in Compressed Sparse Row format>

In [ ]:
cv.vocabulary_

{'narendra damodardas modi': 48,
 'damodardas modi gujarati': 13,
 'modi gujarati end': 46,
 'gujarati end mod': 21,
 'end mod modi': 15,
 'mod modi listen': 41,
 'modi listen born': 47,
 'listen born september': 33,
 'born september indian': 10,
 'september indian politician': 69,
 'indian politician served': 28,
 'politician served th': 56,
 'served th prime': 70,
 'th prime minister': 77,
 'prime minister india': 58,
 'minister india since': 39,
 'india since may': 26,
 'modi chief minister': 45,
 'chief minister gujarat': 11,
 'minister gujarat member': 38,
 'gujarat member parliament': 20,
 'member parliament mp': 37,
 'parliament mp varanasi': 53,
 'member bharatiya janata': 36,
 'bharatiya janata party': 6,
 'janata party bjp': 30,
 'party bjp rashtriya': 54,
 'bjp rashtriya swayamsevak': 8,
 'rashtriya swayamsevak sangh': 64,
 'swayamsevak sangh right': 75,
 'sangh right wing': 67,
 'right wing hindu': 65,
 'wing hindu nationalist': 81,
 'hindu nationalist paramilitary': 25,
 '

In [ ]:
corpus

['narendra damodardas modi gujarati n end mod modi listen born september b indian politician served th prime minister india since may',
 'modi chief minister gujarat member parliament mp varanasi',
 'member bharatiya janata party bjp rashtriya swayamsevak sangh r right wing hindu nationalist paramilitary volunteer organisation',
 'longest serving prime minister outside indian national congress',
 'modi born raised vadnagar northeastern gujarat completed secondary education',
 'introduced r age eight',
 'account helping father sell tea vadnagar railway station reliably corroborated',
 'age married jashodaben modi abandoned soon publicly acknowledging four decade later legally required',
 'modi became full time worker r gujarat',
 'r assigned bjp held several position within party hierarchy rising rank general secretary',
 'c']

In [ ]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi listen born september b indian politician served th prime minister india since may'

In [ ]:
x[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [ ]:

 from sklearn.feature_extraction.text import TfidfVectorizer
 cv=TfidfVectorizer(ngram_range=(1,1),max_features=3)
 x=cv.fit_transform(corpus)



In [ ]:
x[0].toarray

<bound method _cs_matrix.toarray of <1x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>>

In [ ]:
x.shape

(11, 1)

In [ ]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi listen born september b indian politician served th prime minister india since may'

In [ ]:
x[1].toarray()

array([[0.61418897, 0.61418897, 0.49552379]])

In [ ]:
#word2vec continouse bag of words
!pip install ginsim


In [ ]:
import gensim

In [ ]:
from gensim.models import word2vec,keyedvectors

In [ ]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')

[=================================================-] 100.0% 1662.3/1662.8MB downloaded


In [ ]:
vec_king=wv['king']

In [ ]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
vec_king.shape

(300,)

In [ ]:
wv['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [ ]:
wv.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [ ]:
wv.most_similar('man')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [ ]:
wv.most_similar('love')

[('loved', 0.6907791495323181),
 ('adore', 0.6816873550415039),
 ('loves', 0.661863386631012),
 ('passion', 0.6100708842277527),
 ('hate', 0.600395679473877),
 ('loving', 0.5886635780334473),
 ('Ilove', 0.5702950954437256),
 ('affection', 0.5664337873458862),
 ('undying_love', 0.5547304749488831),
 ('absolutely_adore', 0.5536840558052063)]

In [ ]:
wv.similarity('best','good')

0.54671955

In [ ]:
wv.similarity('man','women')

0.2883053

In [ ]:
vec=wv['king']-wv['man']+wv['women']

In [ ]:
wv.most_similar([vec])

[('king', 0.6478992700576782),
 ('queen', 0.535493791103363),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364248752594),
 ('kumaris', 0.49238473176956177),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('kings_princes', 0.42342400550842285)]